### ISSUE TITLE
json mapping files

### ISSUE THREAD

**Issue by dmurphy4100** [altova/SECDB#3]
After looking over the json mapping files that you have provided I am trying to understand the use of "add-to" and "allow". Am I right to assume that "add-to" is a sum of the mapped us-gaap tags to the schema  data element and "allow" is an aggregation of the previously mapped schema elements into a calculated value? Thank you for your assistance.

**Comment by afalk42** [comment]
The JSON mapping files are used to "normalize" the data, i.e. to compute a standardized higher-level representation of the financials statements so that they can be more easily compared between companies and utilized in financial analysis, e.g. in a mobile app.

The main idea here is to blend the hierarchies specified in the calculation linkbase of each company’s extension taxonomy with some globally predefined way to classify the US-GAAP concepts. This is necessary as usually the calculation linkbase in the extension taxonomy does not contain a detailed enough breakdown to accurately classify each reported fact.

The ‘add-to’ key specifies the target line item in our standardized financial report (denoted by its DB field name, see https://github.com/altova/SECDB/blob/master/docs/DB-SCHEMA.md) where the fact value should be added to. It can contain several entries as this data was automatically engineered from past filings and many filings are not consistent and use the same concept to report different things.

The ‘allowed’ key is present on higher-level concepts that represent breakdowns of several other values. It is a list of report line item DB fields that are summarized by this concept. This list is then intersected with the ‘add-to’ list of potential calculation child items to figure out the exact line item that they should be added to. For example, AccountsAndNotesReceivableNet can denote either the current or non-current (long-term) value depending on the actual filing.

```
"AccountsAndNotesReceivableNet": {
    "add-to": [
        "receivablesNet",
        "longTermInvestments"
    ]
}
```

Then, if a particular filing has a calculation linkbase that breaks down AssetsNoncurrent into AccountsAndNotesReceivableNet amongst others, the ‘add-to’ list would be intersected with the ‘allowed’ list and the AccountsAndNotesReceivableNet fact would be added to the longTermInvestments line item in our standardized report.

```
"AssetsNoncurrent": {
    "allowed": [
        "longTermInvestments",
        "propertyPlantAndEquipmentGross",
        "accumulatedDepreciation",
        "propertyPlantAndEquipmentNet",
        "goodwill",
        "intangibleAssets",
        "nonCurrrentAssetsOther",
        "deferredLongTermAssetCharges"
    ],
    "other": "nonCurrrentAssetsOther",
    "total": "nonCurrentAssetsTotal"
},
```

The ‘total’ key (if present) links the value of the fact directly to a report line item. If such a fact is present, it’s value will be used directly without any summation over its child items. Finally, the ‘other’ key represents a report sub-line where all other/uncategorized facts are aggregated to, e.g. any unclassified company extension concepts.
